[project]
name = "ascend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub>=1.1.2",
    "openmind-hub>=1.3.0",
    "pysocks>=1.7.1",
    "socksio>=1.0.0",
]
